/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.82
 * Generated at: 2018-07-17 06:10:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n");
      out.write("<script src=\"/resources/js/login.js\"></script>\n");
      out.write("<script src=\"http://dmaps.daum.net/map_js_init/postcode.v2.js\"></script>\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/login.css\">\n");
      out.write("<title>Home</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<!-- ë¡ê·¸ì¸ ëª¨ë¬ -->\n");
      out.write("<div id=\"loginModal\" class=\"modal\">\n");
      out.write("  <form class=\"modal-content animate\" action=\"javascript:login()\" id=\"loginForm\">\n");
      out.write("    <div class=\"imgcontainer\">\n");
      out.write("      <span onclick=\"document.getElementById('loginModal').style.display='none'\" class=\"close\" title=\"Close Modal\">&times;</span>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"container\">\n");
      out.write("      <h1>Login</h1>\n");
      out.write("      <br><br>\n");
      out.write("      <label for=\"Email\"><b>Email</b></label>\n");
      out.write("      <input type=\"text\" placeholder=\"Enter Email-address\" name=\"email\" id=\"emailsign\" required>\n");
      out.write("      <label for=\"psw\"><b>Password</b></label>\n");
      out.write("      <input type=\"password\" placeholder=\"Enter Password\" name=\"passwd\" id=\"passwdsign\" required>\n");
      out.write("      <button type=\"button\" onclick=\"login()\">Login</button>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"container\" style=\"background-color:#f1f1f1\">\n");
      out.write("      <button type=\"button\" onclick=\"document.getElementById('loginModal').style.display='none'\" class=\"cancelbtn\">Cancel</button>\n");
      out.write("      <button class=\"buttonforgot\" onclick=\"document.getElementById('loginModal').style.display='none';document.getElementById('pwdfindModal').style.display='block';\" style=\"width:auto;\">Forgot password?</button>\n");
      out.write("    </div>\n");
      out.write("  </form>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- í¨ì¤ìë ì°¾ê¸° ëª¨ë¬ -->\n");
      out.write("<div id=\"pwdfindModal\" class=\"modal\">\n");
      out.write("  <form class=\"modal-content animate\" action=\"/action_page.php\" id=\"pwfindform\">\n");
      out.write("    <div class=\"imgcontainer\">\n");
      out.write("      <span onclick=\"document.getElementById('pwdfindModal').style.display='none'\" class=\"close\" title=\"Close Modal\">&times;</span>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"container\">\n");
      out.write("      <label for=\"Email\"><h1>Forgot Password?</h1></label>\n");
      out.write("      <br><br>\n");
      out.write("      <input type=\"text\" placeholder=\"Enter Email address\" name=\"findemail\" required>\n");
      out.write("      <button type=\"button\" onclick=\"certification()\">Send My Password</button>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"container\" style=\"background-color:#f1f1f1\">\n");
      out.write("      <button type=\"button\" onclick=\"document.getElementById('pwdfindModal').style.display='none'\" class=\"cancelbtn\">Cancel</button>\n");
      out.write("    </div>\n");
      out.write("  </form>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<!-- íìê°ì ëª¨ë¬ -->\n");
      out.write("<div id=\"signupModal\" class=\"modal\">\n");
      out.write("  <span onclick=\"document.getElementById('signupModal').style.display='none'\" class=\"close\" title=\"Close Modal\">&times;</span>\n");
      out.write("  <form class=\"modal-content\"  id=\"userRegistForm\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("      <h1>Sign Up</h1>\n");
      out.write("      <p>Please fill in this form to create an account.</p>\n");
      out.write("      <hr>\n");
      out.write("      <label for=\"email\"><b>Email</b></label>\n");
      out.write("      <input type=\"text\" placeholder=\"Enter Email\" name=\"email\" required class=\"email\" id=\"email\" oninput=\"checkId()\">\n");
      out.write("      <label for=\"name\"><b>Name</b></label>\n");
      out.write("      <input type=\"text\" placeholder=\"Enter name\" name=\"name\" id=\"name\" required>\n");
      out.write("      <label for=\"address\"><b>Address</b></label>\n");
      out.write("      <input type=\"text\" placeholder=\"Enter Address\" name=\"address\" id=\"address\" required onclick=\"setAddr()\" readonly>\n");
      out.write("      <input type=\"text\" placeholder=\"\" name=\"dt-address\" id=\"dt-address\" required>\n");
      out.write("      <label for=\"phone\"><b>Phone-number</b></label>\n");
      out.write("      <input type=\"text\" placeholder=\"Enter phone-number\" name=\"phone\" id=\"phone\" required>\n");
      out.write("      <label for=\"pswd\"><b>Password</b></label>\n");
      out.write("      <input type=\"password\" placeholder=\"Enter Password\" name=\"passwd\" required class=\"pswd\" oninput=\"checkPwd()\">\n");
      out.write("      <label for=\"psw-repeat\"><b>Repeat Password</b></label>\n");
      out.write("      <input type=\"password\" placeholder=\"Repeat Password\" name=\"psw-repeat\"  required class=\"pswd\" id=\"repwd\" oninput=\"checkPwd()\">\n");
      out.write("      <div class=\"clearfix\">\n");
      out.write("        <button type=\"button\" class=\"signupbtn\" onclick=\"join()\">Sign Up</button>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </form>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<!-- ìë¡ë ëª¨ë¬ -->\n");
      out.write("<div id=\"uploadModal\" class=\"modal\">\n");
      out.write("  <form class=\"modal-content animate\" id=\"fileForm\" action=\"uploadForm.do\" method=\"post\" enctype=\"multipart/form-data\">\n");
      out.write("    <div class=\"imgcontainer\">\n");
      out.write("      <span onclick=\"document.getElementById('uploadModal').style.display='none'\" class=\"close\" title=\"Close Modal\">&times;</span>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"container\">\n");
      out.write("      <h1>Profile Image</h1>\n");
      out.write("      <br><br>\n");
      out.write("      <label for=\"Email\"><b>Profile Image Select</b></label>\n");
      out.write("      <input type=\"file\" name=\"file\" multiple=\"multiple\" id=\"imagefile\">\n");
      out.write("    <!--   <input type=\"file\" name=\"file\"> -->\n");
      out.write("      <button type=\"button\" onclick=\"upload()\">upload</button>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"container\" style=\"background-color:#f1f1f1\">\n");
      out.write("      <button type=\"button\" onclick=\"document.getElementById('uploadModal').style.display='none'\" class=\"cancelbtn\">Cancel</button>\n");
      out.write("    </div>\n");
      out.write("  </form>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("//Get the modal\n");
      out.write("var modal1 = document.getElementById('loginModal');\n");
      out.write("var modal2 = document.getElementById('signupModal');\n");
      out.write("var modal3 = document.getElementById('pwdfindModal');\n");
      out.write("var modal4 = document.getElementById('uploadModal');\n");
      out.write("window.onclick = function(event) {\n");
      out.write("    if (event.target == modal1) {\n");
      out.write("        modal1.style.display = \"none\";\n");
      out.write("        location.reload();\n");
      out.write("    } \n");
      out.write("    \n");
      out.write("    if (event.target == modal3) {\n");
      out.write("    \tmodal3.style.display = \"none\";\n");
      out.write("        location.reload();\n");
      out.write("    } \n");
      out.write("    \n");
      out.write("    if (event.target == modal2) {\n");
      out.write("        modal2.style.display = \"none\";\n");
      out.write("        location.reload();\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    if (event.target == modal4) {\n");
      out.write("        modal4.style.display = \"none\";\n");
      out.write("        location.reload();\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
