/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.82
 * Generated at: 2018-07-20 07:27:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class view_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/view.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background:#e9eef7;\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"contents_wrap\">\r\n");
      out.write("\t<div class=\"top_menu\">\r\n");
      out.write("\t\t<div class=\"seat_level\">등급/좌석선택</div>\r\n");
      out.write("\t\t<div class=\"ticket_check\">배송선택/매수확인/결제</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"contents\" style=\"background: #f00000;\">\r\n");
      out.write("\t<div class=\"contents_top\">\r\n");
      out.write("\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${match.get(0).match_himage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" class=\"image\"><input type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${match.get(0).match_home}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("     VS     ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${match.get(0).match_away}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" class=\"home\" readonly><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${match.get(0).match_aimage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" class=\"image\" readonly> <input type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${match.get(0).match_stadium}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" class=\"detail\" readonly> <input type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${match.get(0).match_date}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" class=\"detail\" readonly>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"contents_left\">\r\n");
      out.write("\t\t<table border=\"1\" class=\"table_left\">\r\n");
      out.write("\t\t\t<tr class=\"choice\">\r\n");
      out.write("\t\t\t\t<td rowspan=\"3\" class=\"choicestyle\">W</td>\r\n");
      out.write("\t\t\t\t<td style=\"font-size: 31px;background-color: rgb(251, 251, 251);font-weight: bold;\">N</td>\r\n");
      out.write("\t\t\t\t<td rowspan=\"3\" class=\"choicestyle\">E</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td style='background-image : url(\"/resources/image/stadium.jpg\");background-size: cover;width: 50%;height: 40%;'></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr class=\"choice\">\r\n");
      out.write("\t\t\t\t<td style=\"font-size: 31px;background-color: rgb(251, 251, 251);font-weight: bold;\" id=\"se4\">S</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("   \t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"contents_right\">\r\n");
      out.write("  \t\t<table border=\"none\" class=\"table_right\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"topstyle\">등급</td>\r\n");
      out.write("\t\t\t\t<td class=\"topstyle\">가격</td>\r\n");
      out.write("\t\t\t\t<td class=\"topstyle\">잔여석</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>E석</td>\r\n");
      out.write("\t\t\t\t<td>15,000</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${esection}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("석</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>W석</td>\r\n");
      out.write("\t\t\t\t<td>15,000</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${wsection}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("석</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>S석</td>\r\n");
      out.write("\t\t\t\t<td>20,000</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ssection}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("석</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>N석</td>\r\n");
      out.write("\t\t\t\t<td>20,000</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nsection}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("석</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("   \t\t</table>\r\n");
      out.write("   \t\t<div class=\"button\">\r\n");
      out.write("   \t\t\t<button class=\"bt\" onclick=\"closewindow()\">Prev</button>\r\n");
      out.write("   \t\t\t<button class=\"bt\" onclick=\"checkseat()\">Next</button>\r\n");
      out.write("   \t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- 좌석 선택 모달창 -->\t\r\n");
      out.write("<div id=\"seatModal\" class=\"modal\">\r\n");
      out.write("<!-- \t<button type=\"button\" class=\"resv\" onclick=\"reload()\">새로고침</button> -->\r\n");
      out.write("\t<input type=\"hidden\" name=\"cols\" value=\"10\" />\r\n");
      out.write("  \t<input type=\"hidden\" name=\"rows\" value=\"10\" />\r\n");
      out.write("\t<div class=\"wrap\">\r\n");
      out.write("\t\t<fieldset class=\"fieldset\">\r\n");
      out.write("\t    <p class=\"result\" id=\"rst\"></p>\r\n");
      out.write("\t\t</fieldset>\r\n");
      out.write("\t    <ul class=\"colsHead\"></ul>\r\n");
      out.write("\t    <ul class=\"rowsHead\"></ul>\r\n");
      out.write("\t    <ol class=\"seat\"></ol>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("/* \tsetInterval(function() {\r\n");
      out.write("\t\tif( '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("' == null ){\r\n");
      out.write("\t\t\talert(\"세션이 종료되었습니다. 다시 로그인 해주시기 바랍니다.\");\r\n");
      out.write("\t\t\tvar address = \"main.do\";\r\n");
      out.write("\t\t\tlocation.replace(address);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}, 1000); */\r\n");
      out.write("\t\r\n");
      out.write("\t// 모달창 닫기\r\n");
      out.write("\tvar modal1 = document.getElementById('seatModal');\r\n");
      out.write("\twindow.onclick = function(event) {\r\n");
      out.write("\t     if (event.target == modal1) {\r\n");
      out.write("\t        /* modal1.style.display = \"none\"; */\r\n");
      out.write("\t\t\tlocation.reload();\r\n");
      out.write("\t    }\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\tvar $cols = $('input[name=cols]'),\r\n");
      out.write("\t$rows = $('input[name=rows]'),\r\n");
      out.write("\t$result = $('.result'),\r\n");
      out.write("\t$seat = $('.wrap .seat'),\r\n");
      out.write("\t$colsHead = $('.wrap .colsHead'),\r\n");
      out.write("\t$rowsHead = $('.wrap .rowsHead'),\r\n");
      out.write("\tcolsNum = 0, rowsNum = 0;\r\n");
      out.write("\r\n");
      out.write("\t// 화면 업데이트\r\n");
      out.write("\tvar updateView = function() {\r\n");
      out.write("\tvar makeTag = '', i = 1, leng = 0;\r\n");
      out.write("\r\n");
      out.write("\tcolsNum = parseInt($cols.val() || 0, 10);\r\n");
      out.write("\trowsNum = parseInt($rows.val() || 0, 10);\r\n");
      out.write("\tfor(i = 1, leng = colsNum * rowsNum; i <= leng; i++) {\r\n");
      out.write("\t    if( i % colsNum === 1 ) {\r\n");
      out.write("\t        makeTag += \"<li class='ll' style='clear:both;'></li>\";\r\n");
      out.write("\t    } else {\r\n");
      out.write("\t        makeTag += \"<li class='ll'></li>\";\r\n");
      out.write("\t    }\r\n");
      out.write("\t}\r\n");
      out.write("\t$seat.html(makeTag);\r\n");
      out.write("\r\n");
      out.write("\tfor(makeTag = '', i = 1, leng = colsNum; i <= leng; i++) {\r\n");
      out.write("\t    makeTag += '<li>' + i + '</li>';\r\n");
      out.write("\t}\r\n");
      out.write("\t$colsHead.html(makeTag);\r\n");
      out.write("\r\n");
      out.write("\tfor(makeTag = '', i = 65, leng = 65 + rowsNum; i < leng; i++) {\r\n");
      out.write("\t    makeTag += '<li>' + String.fromCharCode(i) + '</li>';\r\n");
      out.write("\t}\r\n");
      out.write("\t$rowsHead.html(makeTag);\r\n");
      out.write("\r\n");
      out.write("\t/* $result.html('nothing'); */\r\n");
      out.write("\t};\r\n");
      out.write("\r\n");
      out.write("\tvar onoff = \"0\";\r\n");
      out.write("\tvar colsIndex=\"\";\r\n");
      out.write("\tvar rowsName=\"\";\r\n");
      out.write("\tvar seat =\"\"; \r\n");
      out.write("\tvar ind = \"\";\r\n");
      out.write("\r\n");
      out.write("\t// 선택한 자리에 대해서 index를 가지고 seat, ind 문자열로 만들기\t\r\n");
      out.write("\tvar getSeatName = function( index ) {\r\n");
      out.write("\t\tcolsIndex = (index % colsNum) + 1;\r\n");
      out.write("\tvar rowsIndex = Math.ceil((index + 1) / colsNum) - 1;\r\n");
      out.write("\t    rowsName = String.fromCharCode((65 + rowsIndex));\r\n");
      out.write("\t    \r\n");
      out.write("\t    if(seat.indexOf(\",\" + rowsName+colsIndex) != -1){\r\n");
      out.write("\t    \tseat = seat.replace(\",\" + rowsName+colsIndex,'');\r\n");
      out.write("\t    \tind = ind.replace(\",\" + index , '');\r\n");
      out.write("\t    } else {\r\n");
      out.write("\t    \tif (seat.indexOf(rowsName+colsIndex) != -1){\r\n");
      out.write("\t    \t\tif(seat.indexOf(\",\") != -1) {\r\n");
      out.write("\t\t    \t\tseat = seat.replace(rowsName+colsIndex + \",\",'');\r\n");
      out.write("\t\t    \t\tind = ind.replace(index +\",\",'');\r\n");
      out.write("\t    \t\t} else {\r\n");
      out.write("\t    \t\t\tseat = seat.replace(rowsName+colsIndex,'');\r\n");
      out.write("\t    \t\t\tind = ind.replace(ind,'');\r\n");
      out.write("\t    \t\t}\r\n");
      out.write("\t    \t} else {\r\n");
      out.write("\t\t\t    if (seat == \"\"){\r\n");
      out.write("\t\t\t\t\tseat = rowsName + colsIndex;\r\n");
      out.write("\t\t\t\t\tind = index;\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t// , 갯수로 4자리 초과 시 좌석 선택 불가\r\n");
      out.write("\t\t\t\t\tvar match = seat.match(/,/g);\r\n");
      out.write("\t\t\t\t\tif( match != null ){\r\n");
      out.write("\t\t\t\t\tvar count = match.length;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\tif( count > 2 ){\r\n");
      out.write("\t\t\t\t\t\talert(\"4좌석까지만 선택 가능합니다.\");\r\n");
      out.write("\t\t\t\t\t\tonoff = \"1\";\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\tseat += \",\" + rowsName + colsIndex;\r\n");
      out.write("\t\t\t\t\t\tind += \",\" + index;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t    \t}\r\n");
      out.write("\t    }\r\n");
      out.write("\t    \r\n");
      out.write("\t\treturn rowsName + ' cols ' + colsIndex + '';\r\n");
      out.write("\t};\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t var values = \"\";\r\n");
      out.write("\t var level = \"\";\r\n");
      out.write("\t var date = \"\";\r\n");
      out.write("\t // 구역 선택 시 해당 구역 seat정보 불러오기\r\n");
      out.write("\t$('.choice').on('click', 'td', function() {\r\n");
      out.write("\t\t\tvar $levelchoice = $(this);\r\n");
      out.write("\t\t    level = $levelchoice.text();\r\n");
      out.write("\t\t    $('#rst').text(level);\r\n");
      out.write("\t\t    date=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${match.get(0).match_date}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\";\r\n");
      out.write("\t\t  \t/* $(\".seat li\").css(\"background\",\"none\"); */\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t  method: \"POST\",\r\n");
      out.write("\t\t\t\t  url: \"seatselect.do\",\r\n");
      out.write("\t\t\t\t  data: {\r\n");
      out.write("\t\t\t\t\t  level : level,\r\n");
      out.write("\t\t\t\t\t  date : date\r\n");
      out.write("\t\t\t\t  },\r\n");
      out.write("\t\t\t\t  success : function(result){\r\n");
      out.write("\t\t\t\t\t  if(result.code == \"OK\"){\r\n");
      out.write("\t\t\t\t\t\t  \tvalues = result.ticketIndex;\r\n");
      out.write("\t\t\t\t\t\t  \t$.each(values, function( index, value ) {\r\n");
      out.write("\t\t\t\t\t\t  \t\t$(\".seat li\").eq(value).prop(\"disabled\", true);\r\n");
      out.write("\t\t\t\t                $(\".seat li\").eq(value).css(\"background\",\"orange\");\r\n");
      out.write("\t\t\t\t                });\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t \t document.getElementById('seatModal').style.display='block';\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t  }else if(result.code == \"NOT\"){\r\n");
      out.write("\t\t\t\t\t\t  alert(\"good\");\r\n");
      out.write("\t\t\t\t\t  } else {\r\n");
      out.write("\t\t\t\t\t\t alert(\"fail\");\r\n");
      out.write("\t\t\t\t\t  }\r\n");
      out.write("\t\t\t\t  },\r\n");
      out.write("\t\t\t\t  error:function(request,status,error){\r\n");
      out.write("\t\t\t\t        alert(\"code:\"+request.status+\"\\n\"+\"message:\"+request.responseText+\"\\n\"+\"error:\"+error);\r\n");
      out.write("\t\t\t\t  }\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t// 좌석 선택 시 getSeatName 실행 및 배경색 변경\r\n");
      out.write("\t$seat.on('click', 'li', function() {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tvar $this = $(this),\r\n");
      out.write("\t\t\t    index = $this.index();\t\t\t\t\r\n");
      out.write("\t\t \t\tgetSeatName(index);\r\n");
      out.write("\t\t\t\tif( onoff == \"0\"){\r\n");
      out.write("\t\t\t \t \t$this.toggleClass('reserve');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t \t \tif ( onoff == \"1\"){\r\n");
      out.write("\t\t \t \t\tonoff = \"0\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t// 좌석선택 후 NEXT 버튼을 눌러 다음단계로 넘어갈때 \r\n");
      out.write("\tfunction checkseat() {\r\n");
      out.write("\t\tvar price =\"\";\r\n");
      out.write("\t\tif( level ==\"N\" || level == \"S\"){\r\n");
      out.write("\t\t\tprice = \"20000\";\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tprice = \"15000\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif ( seat == \"\"){\r\n");
      out.write("\t\t\talert(\"좌석을 먼저 선택 해주세요\");\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t  method: \"POST\",\r\n");
      out.write("\t\t\t\t  url: \"insertseat.do\",\r\n");
      out.write("\t\t\t\t  data: {\r\n");
      out.write("\t\t\t\t\t  ind : ind,\r\n");
      out.write("\t\t\t\t\t  seat : seat,\r\n");
      out.write("\t\t\t\t\t  date : date,\r\n");
      out.write("\t\t\t\t\t  level : level,\r\n");
      out.write("\t\t\t\t\t  price : price\r\n");
      out.write("\t\t\t\t  },\r\n");
      out.write("\t\t\t\t  success : function(data){\r\n");
      out.write("\t\t\t\t\t  if(data == \"1\"){\r\n");
      out.write("\t\t\t\t\t\t  alert(\"이미 선택된 자리입니다.\");\r\n");
      out.write("\t\t\t\t\t\t  location.reload();\r\n");
      out.write("\t\t\t\t\t  }else{\r\n");
      out.write("\t\t\t\t\t\t  var resvcheck = \"1\";\r\n");
      out.write("\t\t\t\t\t\t  var date=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${match.get(0).match_date}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\";\r\n");
      out.write("\t\t\t\t\t\t  var address = \"reservation.do?resvcheck=\" + resvcheck + \"&date=\"+ date + \"&seat=\" + seat + \"&level=\" + level + \"&price=\" + price;\r\n");
      out.write("\t\t\t\t\t\t  location.replace(address);\r\n");
      out.write("\t\t\t\t\t  }\r\n");
      out.write("\t\t\t\t  },\r\n");
      out.write("\t\t\t\t  error:function(request,status,error){\r\n");
      out.write("\t\t\t\t        alert(\"code:\"+request.status+\"\\n\"+\"message:\"+request.responseText+\"\\n\"+\"error:\"+error);\r\n");
      out.write("\t\t\t\t  }\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction closewindow() {\r\n");
      out.write("\t\twindow.close();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//새로고침 작업으로 예매된 자리 확인가능\r\n");
      out.write("\tfunction reload(){\r\n");
      out.write("\t\tlocation.reload();\r\n");
      out.write("\t  /*  $.ajax({\r\n");
      out.write("\t\t\t  method: \"POST\",\r\n");
      out.write("\t\t\t  url: \"seatselect.do\",\r\n");
      out.write("\t\t\t  data: {\r\n");
      out.write("\t\t\t\t  level : level,\r\n");
      out.write("\t\t\t\t  date : date\r\n");
      out.write("\t\t\t  },\r\n");
      out.write("\t\t\t  success : function(result){\r\n");
      out.write("\t\t\t\t  if(result.code == \"OK\"){\r\n");
      out.write("\t\t\t\t\t  alert(seat);\r\n");
      out.write("\t\t\t\t\t  alert(ind);\r\n");
      out.write("\t\t\t\t\t  \tseat = \"\";\r\n");
      out.write("\t\t\t\t\t  \tind = \"\";\r\n");
      out.write("\t\t\t\t\t  \talert(seat);\r\n");
      out.write("\t\t\t\t\t\t  alert(ind);\r\n");
      out.write("\t\t\t\t\t  \t$(\".seat li\").prop(\"disabled\", false );\r\n");
      out.write("\t\t\t\t\t  \talert(\"1\");\r\n");
      out.write("\t\t\t\t\t    $(\".seat li\").css(\"background\",\"none\");\r\n");
      out.write("\t\t\t\t\t  \talert(\"2\");\r\n");
      out.write("\t\t\t\t\t  \tvalues = result.ticketIndex;\r\n");
      out.write("\t\t\t\t\t  \t$.each(values, function( index, value ) {\r\n");
      out.write("\t\t\t\t\t  \t\t$(\".seat li\").eq(value).prop(\"disabled\", true);\r\n");
      out.write("\t\t\t                $(\".seat li\").eq(value).css(\"background\",\"orange\");\r\n");
      out.write("\t\t\t                });\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t document.getElementById('seatModal').style.display='block'; \r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t  }else if(result.code == \"NOT\"){\r\n");
      out.write("\t\t\t\t\t  alert(\"good\");\r\n");
      out.write("\t\t\t\t  } else {\r\n");
      out.write("\t\t\t\t\t alert(\"fail\");\r\n");
      out.write("\t\t\t\t  }\r\n");
      out.write("\t\t\t  },\r\n");
      out.write("\t\t\t  error:function(request,status,error){\r\n");
      out.write("\t\t\t        alert(\"code:\"+request.status+\"\\n\"+\"message:\"+request.responseText+\"\\n\"+\"error:\"+error);\r\n");
      out.write("\t\t\t  }\r\n");
      out.write("\t\t}) */\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tupdateView();\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
